import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

// This file will be generated by build_runner
// Run: flutter pub run build_runner build

final getIt = GetIt.instance;

@injectableInit
Future<void> configureInjection() async {
  // This function will be generated by build_runner
  // It will contain all the dependency injection setup
  
  // Placeholder for generated code
  // After running build_runner, this will be:
  // await _$configureInjection(getIt);
}

// Manual setup placeholder - replace with generated code after running build_runner
Future<void> setupServiceLocator() async {
  // TODO: This will be auto-generated by injectable
  // Configure all repositories
  // Configure all datasources
  // Configure all use cases
  // Configure all providers
}
