// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB883FNKEverPTY37IChntR7GY-MmeYjUQ',
    appId: '1:733694166310:web:126e3f53e1c68d10512de7',
    messagingSenderId: '733694166310',
    projectId: 'lingoquest-d47b0',
    authDomain: 'lingoquest-d47b0.firebaseapp.com',
    storageBucket: 'lingoquest-d47b0.firebasestorage.app',
    measurementId: 'G-X5FRYENW6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "YOUR_API_KEY",
    appId: '1:733694166310:android:2ad6f7ca6f89368b512de7',
    messagingSenderId: '733694166310',
    projectId: 'lingoquest-d47b0',
    storageBucket: 'lingoquest-d47b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "YOUR_API_KEY",
    appId: '1:733694166310:ios:3a578108c919887d512de7',
    messagingSenderId: '733694166310',
    projectId: 'lingoquest-d47b0',
    storageBucket: 'lingoquest-d47b0.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "YOUR_API_KEY",
    appId: '1:733694166310:ios:3a578108c919887d512de7',
    messagingSenderId: '733694166310',
    projectId: 'lingoquest-d47b0',
    storageBucket: 'lingoquest-d47b0.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "YOUR_API_KEY",
    appId: '1:733694166310:web:b967bedea7f7749d512de7',
    messagingSenderId: '733694166310',
    projectId: 'lingoquest-d47b0',
    authDomain: 'lingoquest-d47b0.firebaseapp.com',
    storageBucket: 'lingoquest-d47b0.firebasestorage.app',
    measurementId: 'G-PW8M8Y00KC',
  );
}
